name = "mcvds_gen"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
htmgrrrl = ">= 0.3.0 and < 1.0.0"
mcvds_types = { path = "../mcvds_types" }
simplifile = ">= 2.2.0 and < 3.0.0"
decode = ">= 0.2.1 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
